### ISSUE TITLE
이 웹사이트의 용도는 무엇인가

### ISSUE THREAD

**Issue by Hyeongrok1** [SKKU-SW-CROSSING/homepage#1]
웹사이트에 뭘 올리고 싶은지 생각해보면 뭘 만들지도 생각할 수 있을 것 같아. 거 한 번 생각을 해봅시다.
일단 내가 생각한 건 이 사이트 제작에 참여한 사람들의 포트폴리오를 담는 사이트인데 약간 블로그처럼 꾸미는 거지. 똥글도 막 싸지르고 저장할 수 있게. 그리고 자기가 만든 제작물 같은 거 올릴 수 있게

**Comment by moseoridev** [comment]
[메인 페이지](https://github.com/SKKU-SW-CROSSING/homepage/blob/main/index.html)에는 팀 소개랑 개인 포폴로 가는 링크 담아두고 개인 폴더 (/moseoridev, /Hyeongrok1 등에는 각자 원하는 포트폴리오를 담는거지

개인 폴더에 commit은 알아서 하되 메인 페이지랑 다른 사용자 페이지 개선점은 PR 넣어서 git 사용법 연습도 하고

어떻습니까
