### ISSUE TITLE
Github Pages /members 404 error

### ISSUE THREAD

**Issue by moseoridev** [SKKU-SW-CROSSING/homepage#5]
[각 멤버별 페이지](https://skku-sw-crossing.github.io/members/moseoridev)가 404 에러로 제대로 표시되지 않음

/index.html로 경로를 지정해줘도 마찬가지

뭐가 문제일까..

**Comment by Hyeongrok1** [comment]
/members/moseridev/index.html 에서 맨 앞의 /을 제거했더니 정상적으로 경로가 지정됐습니다.

**Comment by moseoridev** [comment]
PR #7 으로 해결 완료
